### ISSUE TITLE
Feature request: access data points via API from City of San Jose's Open Data Portal

### ISSUE THREAD

**Issue by mthong** [codeforsanjose/economic-indicators-dashboard#1]
Why:
- Creates central place for data to be updated by OED, separate from the project source code
- Demonstrate how [open data portal](http://data.sanjoseca.gov) can be used 

Requires:
- Data indicators uploaded to the data portal by OED staff (aka @mthong aka. me)
- Junar API to be functional enough to use

**Comment by golgistudio** [comment]
Published site on gh-pages now pulls data from the open data portal.   

There is a console error when selecting the total jobs sector chart

configurations are still being pulled from the gh-pages

**Comment by LaurieSReynolds** [comment]
Current version is just pulling the first 50 records.  Update to retrieve all records from the stream.

**Comment by mthong** [comment]
This seems to be working well now without a limit on the number of records. Thanks @golgistudio! Closing issue.
