### ISSUE TITLE
Tooltip labels for Unemployment Chart 

### ISSUE THREAD

**Issue by mthong** [codeforsanjose/economic-indicators-dashboard#113]
Tooltip labels for unemployment rate show SJ/SJ metro series labels but only occasionally show the data label - and only for one of the two series. 

![image](https://cloud.githubusercontent.com/assets/4636824/17575443/17f55a10-5f1e-11e6-83ea-101d114e69bf.png)

**Comment by golgistudio** [comment]
Note - this displays fine on the SJEconomy site.  Is incorrect in the latest code which is published on gh-pages

**Comment by golgistudio** [comment]
Should be fixed.
