### ISSUE TITLE
Should historical data be available for viewing?

### ISSUE THREAD

**Issue by golgistudio** [codeforsanjose/economic-indicators-dashboard#13]
Once this is published, going forward should user's be able to access data that was published previously?

(e.g. If by the end of the year, there have been quarterly updates - Q2, Q3, Q4 - should user's have access to the previously published data?   (In Q4, can user's still view Q2 and Q3 data including the plots and subplots?)

**Comment by mthong** [comment]
Hmm. Good question. Ideally the historical data will be available in drop-down detail graphs so as time passes the previous data points will get incorporated into the plots and it will be possible to read the specific data point, so it shouldn't be necessary to view a "snapshot" from a previous quarter. But this is a question worth chewing on some more.

**Comment by mthong** [comment]
I don't think the user needs to be able to access a view of the dashboard from prior quarters. The OED economist (currently me) should keep the raw data from past quarters, however.  

At some point maybe we could consider a "download PDF" feature which allows a user to record and print a snapshot of the current dashboard.
