### ISSUE TITLE
Change color for the more detail button

### ISSUE THREAD

**Issue by golgistudio** [codeforsanjose/economic-indicators-dashboard#22]
bright green detail button is too eye-catching; draws attention away from indicator.

**Comment by mthong** [comment]
Suggest changing button to grey downward arrow ("V" shape) with the text "see more." This could toggle to a upward arrow with the text "see less."

**Comment by golgistudio** [comment]
See the options menu example with the 'V' shape on the link below

http://ux.stackexchange.com/questions/72793/should-a-view-more-button-move-down-when-the-pane-expands/72796

**Comment by mthong** [comment]
thanks @dshapira! can we remove button border and shading so it is even more subtle (not even like a button anymore)? E.g. see "Details" arrow on [this MBTA dashboard](http://www.mbtabackontrack.com/performance/index.html#/home)

**Comment by mthong** [comment]
looking good! one more tweak: change the "see more/see less" font style from Times New Roman to something sans serif, either arial or the font used for the rest of the text?
