### ISSUE TITLE
All three rows of dashboard should be visible on a laptop display

### ISSUE THREAD

**Issue by golgistudio** [codeforsanjose/economic-indicators-dashboard#25]

**Comment by mthong** [comment]
Visually I think the rows might benefit from a bit more spacing. We've also added a sentence of text at the top that pushes the rows down. Could possibly make each row a little shorter by reducing height of the title area. 

We've also added a fourth row of indicators and may add a fifth, but I think the goal of having three rows of indicators visible is a good one. 

Needs discussion. Not high priority for MVP.

**Comment by mthong** [comment]
After talking with @dshapira, and adding additional indicator rows, this goal doesn't seem that important anymore.
