### ISSUE TITLE
info icon hover - change behavior from float to solid

### ISSUE THREAD

**Issue by golgistudio** [codeforsanjose/economic-indicators-dashboard#31]
When hovering or selecting the info icon, the source for the box should display as a tooltip.   This should fade out slowly when the user moves away.

**Comment by mthong** [comment]
I think listing the source in a tooltip works well. Is it typical for the tooltip text and box to move around following the users' cursor? Just wondering if it would look "neater" if the tooltip appeared at one location and stayed there. Very minor issue - not high priority, certainly not for the initial preview.

**Comment by golgistudio** [comment]
Tooltip is using react-tooltip which provides the option of float or solid.

Change behavior to solid.   See this link for an example: http://wwayne.com/react-tooltip/

**Comment by golgistudio** [comment]
Switched to solid style
