### ISSUE TITLE
Drill down charts should display side by side

### ISSUE THREAD

**Issue by golgistudio** [codeforsanjose/economic-indicators-dashboard#35]
If an indicator has drill down charts, the two charts should display side by side

**Comment by mthong** [comment]
Is it possible to make the jobs by sector bar chart appear at the same time as the jobs over time line chart? (without needing to click on the line chart?)

**Comment by mthong** [comment]
I think it is important to have the jobs by sector bar chart appear without clicking on the time series. Will create a new issue for it. 
But we don't necessarily need the two charts to be side by side. At this point, for the Beta milestone, let's just say we'll do whatever is the easiest to make work for formatting (and with the other indicators that may or may note have one or two detail charts)

**Comment by mthong** [comment]
If there are two charts, I don't think they need to be side by side. Closing issue.
