### ISSUE TITLE
Charts should display under selected indicator box

### ISSUE THREAD

**Issue by golgistudio** [codeforsanjose/economic-indicators-dashboard#37]
When the view window is narrow and the indicator boxes display on multiple rows, the more details charts display below all of the indicator boxes for that group.  

Expected behavior that it should display directly under the selected indicator.   As this is using bootstrap row-fluid policy, this may be difficult.

Should we do this or is it ok to leave behavior as is?

**Comment by mthong** [comment]
Overall I think it is fine - but definitely means we (I) have to provide titles for the charts (which they need anyway).

I think it would be ideal for the detail charts to display under the indicator box it "belongs" to, with the other indicator boxes then starting a new row below the charts, BUT I think it is fine to leave the behavior as-is if it is difficult.

**Comment by mthong** [comment]
Issue #86 solves this by changing behavior to allow detail chart(s) for only one indicator to open at a time.
