### ISSUE TITLE
tooltip should always display on top

### ISSUE THREAD

**Issue by golgistudio** [codeforsanjose/economic-indicators-dashboard#38]
In chrome, hovering over the first housing indicator info icon, the tooltip is partially obscured by the Housing label

**Comment by dshapira** [comment]
Please also make tooltip font size same size as the small dashboard-date indicator element.

**Comment by mthong** [comment]
Is this still open?

**Comment by mthong** [comment]
Okay, after examining the site, it looks like the data source tooltip, the one that appears when user hovers over the (i) symbol, is still a larger font size than the dashboard-date indicator element.

**Comment by golgistudio** [comment]
Fixed font size

The tooltip still appears underneath the trend icon in some cases - total jobs or unemployment rate

**Comment by golgistudio** [comment]
Looks like this is fixed with the latest version update
