### ISSUE TITLE
footer should always be anchored to the bottom of the viewport

### ISSUE THREAD

**Issue by golgistudio** [codeforsanjose/economic-indicators-dashboard#39]
In browser displays on large screens, there is space between the footer and the bottom of the browser window.

The footer should always be anchored to the bottom.

**Comment by mthong** [comment]
When @dshapira and I looked at this issue, it seemed to be a problem only in rare cases with a very wide screen or very little data, so I labeled it as low priority for our initial release.

**Comment by golgistudio** [comment]
Closing as a duplicate to #73
