### ISSUE TITLE
Text in row labels should be centered vertically

### ISSUE THREAD

**Issue by golgistudio** [codeforsanjose/economic-indicators-dashboard#41]
Currently the text is shifted slightly towards the bottom.  

It would be nice if it was centered in the middle.

**Comment by mthong** [comment]
Do you mean the "jobs" "talent" "real estate" labels? Just asking for clarification.

**Comment by golgistudio** [comment]
yes

**Comment by mthong** [comment]
The labels still become off-centered on a wide screen. I'll share a screenshot from my work monitor.

**Comment by golgistudio** [comment]
Issue # 76 covers the wide screen case and has a screenshot.  Can this issue be closed?

**Comment by mthong** [comment]
Ok, closing this issue but note that that centering is still a problem as noted in #76.
