### ISSUE TITLE
Add "About" page or pop-up

### ISSUE THREAD

**Issue by mthong** [codeforsanjose/economic-indicators-dashboard#42]
Add an "About" page or pop-up that explains the who/what/why/how of the site. It can be very simple in layout - but should be consistent with the look and feel of the dashboard. 

The [http://howsbusinesschicago.org](http://howsbusinesschicago.org/) site has a very detailed about page. I don't think we need to get into all the data methodology details, but I think we should at least cover the following. 

- Why the dashboard was built 
- Add email link (to Michelle) for people to provide feedback on the site

Also include some fun civic tech details: 
- Team: who made the site 
- Mention the site is open source, and link to Github repo

I will write up some text and put it in a textfile in the github-pages branch.

**Comment by golgistudio** [comment]
We took a snapshot of How's Business for the Dashboards project

https://github.com/codeforsanjose/dashboards

http://codeforsanjose.github.io/dashboards/dashboards/fire-incidents/about/

Propose adding the html and css as static pages in the gh-pages so they can be updated without having to redeploy the site

**Comment by golgistudio** [comment]
If this will eventually be hosted on SJEconomy - use a copy of their current about page for the template.

**Comment by mthong** [comment]
Here are some web content formatting guidelines from our design agency for the sjeconomy.com site. [CoSJ_ContentFormattingGuide.pdf](https://github.com/codeforsanjose/economic-indicators-dashboard/files/249746/CoSJ_ContentFormattingGuide.pdf)

**Comment by LaurieSReynolds** [comment]
Is this dashboard meant to be a Code for San Jose or the SJEconomy site?  If it is a Code for San Jose site like Chicago's How's Business site, the details about the code with links to github are fine.  If it meant to be a SJEconomy site, then it doesn't make sense to include  those details.

**Comment by golgistudio** [comment]
ps - is it possible for someone on your SJEconomy website to create an about page with a feedback form and we could link to that?

**Comment by mthong** [comment]
I think at the current stage of the project it is most appropriate for the about page to have the same style as the dashboard itself, even though it is possible for me to create an about page using the SJEconomy Wordpress template.

**Comment by golgistudio** [comment]
Page added
