### ISSUE TITLE
Get rid of max number labels on chart axes

### ISSUE THREAD

**Issue by mthong** [codeforsanjose/economic-indicators-dashboard#43]
The charts seem to have a default behavior of displaying the max value of each axis in bold, which is strange and unnecessary "chart junk" to my eyes. E.g. If the labor force Y axis is increasing in intervals of 100,000, it's fine for 500,000 or 600,000 to be the max label -- I don't need to see the number "604,399.4" in bold at the end of the Y axis.

**Comment by mthong** [comment]
Hmm, after looking at a bunch of [NVD3 examples](http://nvd3-community.github.io/nvd3/examples/site.html) it looks like it's the norm to display the max/min axis value in bold. I've never seen that before as a convention for labeling axes. I looked through the documentation and didn't see anything obvious about disabling this behavior.

**Comment by golgistudio** [comment]
Removed max labels
