### ISSUE TITLE
Add titles for drill down charts

### ISSUE THREAD

**Issue by mthong** [codeforsanjose/economic-indicators-dashboard#45]
@golgistudio What is the best way for me to specify the title (i.e. least amount of work for you)? I think we discussed the idea of adding an extra column after each detail filename in indicators.csv. If I do that I would probably leave it to you to update the filename in latest_indicators.csv to avoid breaking the current working site.

**Comment by LaurieSReynolds** [comment]
Let's create a configuration file.  I'll create a stub one - json format and post it

**Comment by mthong** [comment]
Related question @golgistudio : how hard/annoying would it be to allow me to add # comments at the beginning or end of the CSV files? I.e. pre-process all CSVs to ignore those lines for grabbing and visualizing data?

**Comment by golgistudio** [comment]
Currently, this is not supported, we would need to make some coding changes

What are your goals for adding comments to csv files?

As the eventual goal is to host this in data.sanjose.gov - consider handling notes as it is done for the fire incidents.   Which does not seem to be in the csv

http://data.sanjoseca.gov/dataviews/226237/san-jose-fire-incidents-jan-2015/

**Comment by mthong** [comment]
Good point. I think you're right it's best to not include "features" that are not standard for CSVs. 
My desires were:
(1) to allow myself to leave "placeholder" indicators in the CSV that are not yet live due to lack of data 
(2) to leave some metadata in the CSV file itself - this is just a problem with CSVs generally
