### ISSUE TITLE
Change job sector bar chart to be horizontal

### ISSUE THREAD

**Issue by mthong** [codeforsanjose/economic-indicators-dashboard#47]
[http://nvd3-community.github.io/nvd3/examples/multiBarHorizontalChart.html](http://nvd3-community.github.io/nvd3/examples/multiBarHorizontalChart.html)

**Comment by mthong** [comment]
if you can make the formatting work

**Comment by mthong** [comment]
Industry treemaps are also cool - but I don't think NVD3 supports them. 
http://www.politicalmathblog.com/BLS/2012/06/

**Comment by mthong** [comment]
Maybe the config file or indicator CSV should specify what type each "detail chart" should be. E.g. pie, line, donut. This would require the city economist (currently me) to know what options are available in NVD3 but that seems reasonable.

**Comment by golgistudio** [comment]
Implemented
