### ISSUE TITLE
Communicate that this is a beta version

### ISSUE THREAD

**Issue by mthong** [codeforsanjose/economic-indicators-dashboard#48]
Header at top should read "SAN JOSE ECONOMIC INDICATORS _beta_" 

Feel free to stylize the "beta" as needed to make it look good.

**Comment by LaurieSReynolds** [comment]
Beta is very application software oriented, but this is more of a report - How about draft or preview?

What are you trying to communicate through the term beta?  Does it apply to the indicator values, or just the site design?

**Comment by mthong** [comment]
In my mind "beta" applies to the overall dashboard: the chart interactivity, the features (like being able to download data) and which indicators are included and not included. (The indicator values are official numbers that I will stand by.) 

Trying to communicate that this is a first version of the dashboard, not necessarily polished down to every last detail, that we want user feedback and based on that feedback may add/remove features and refine the look & feel in the future. Intending to take the pressure off what we show at the Council meeting. 

I know it's not a full fledged app but doesn't beta get used as for websites as well?

**Comment by mthong** [comment]
I'm not wed to the term beta (and it may be confusing to non-tech users) but I don't think draft or preview quite capture what I want to convey either...

If you think beta is misleading or inaccurate, maybe on the about page we just say that this site is a work in progress?

**Comment by LaurieSReynolds** [comment]
What do other SJ websites use to communicate the same concept?  

If Beta best represents what you are trying to communicate - let's stick with that.

**Comment by mthong** [comment]
It is rare in conventional gov tech procurement for there to be an MVP or beta release used to incorporate user feedback into the development process, but some civic tech pioneers have started to evangelize this approach for gov digital services (E.g. [USDS Playbook #4](https://playbook.cio.gov/#play4) and the [VA's vets.gov beta release](https://www.vets.gov/2015/11/11/why-we-are-designing-in-beta.html)). 

Recently the City of San Jose has used the term "demo" or more frequently "pilot" to convey a similar meaning, but given the broader usage in civic tech circles I think "beta" is still the best term.

**Comment by LaurieSReynolds** [comment]
Ok - thanks for the clarification.  I thought the target audience was city council team and SJ  community.  Now, I understand this is for your fellow civic techies.

**Comment by mthong** [comment]
I have reconsidered the issue and I think we can drop the beta from the header, and instead change the footer to say "A demonstration project by the San Jose Office of Economic Development and Code for San Jose."
