### ISSUE TITLE
Add icons for main indicator categories: jobs/talent/real estate

### ISSUE THREAD

**Issue by mthong** [codeforsanjose/economic-indicators-dashboard#5]
Thinking we can find some icons from https://thenounproject.com

Links to icons that Michelle posted to slack

Briefcase - Jobs
https://thenounproject.com/search/?q=jobs&i=28952

People - Talent
https://thenounproject.com/search/?q=people&i=9477

**Comment by golgistudio** [comment]
Proposed icons 

Jobs (id badge)
https://thenounproject.com/search/?q=jobs&i=344179

or Economics 
https://thenounproject.com/search/?q=banking&i=175469

Talent (meeting)
https://thenounproject.com/search/?q=meetings&i=28971

Real estate
https://thenounproject.com/search/?q=real+estate&i=179141

**Comment by golgistudio** [comment]
Michelle - Is this still needed or can we close this?

**Comment by mthong** [comment]
We can close it. No need for icons.
