### ISSUE TITLE
Host dashboard on sjeconomy.com

### ISSUE THREAD

**Issue by mthong** [codeforsanjose/economic-indicators-dashboard#50]
Coordinate with @mthong for access.

**Comment by golgistudio** [comment]
Michelle did this

**Comment by golgistudio** [comment]
Michelle published to the SJeconomy site.  It can be seen here:

[http://sjeconomy.com/indicators/#/?_k=b8bqvg](http://sjeconomy.com/indicators/#/?_k=b8bqvg)
