### ISSUE TITLE
Change footer text

### ISSUE THREAD

**Issue by mthong** [codeforsanjose/economic-indicators-dashboard#53]
Change from right-aligned "San Jose Office of Economic Development" to centered text that reads "A Demonstration Project of the San Jose Office of Economic Development and Code for San Jose" 

Feel free to suggest something a bit snappier for "Demonstration Project"...

Made the font a more visible color than the current light grey. Maybe the lime green? It's ok for it to pop a little.

**Comment by mthong** [comment]
As an example, I like the footer of the DataSF page. It's subtle but friendly in communicating "this isn't  your usual institutional gov website." 

https://datasf.org/progress/

**Comment by golgistudio** [comment]
Configurable in the config file
