### ISSUE TITLE
Fix unemployment chart: values are rounded to nearest integer

### ISSUE THREAD

**Issue by mthong** [codeforsanjose/economic-indicators-dashboard#55]
Compare the values in the chart with the values in the CSV: 
https://github.com/codeforsanjose/economic-indicators-dashboard/blob/gh-pages/data/monthly_unemployment_march2016.csv

At some point the values are being rounded to the nearest integer!

**Comment by golgistudio** [comment]
Fixed - was using parseInt instead of parseFloat
