### ISSUE TITLE
Add SJ metro and State comparison to unemployment line chart

### ISSUE THREAD

**Issue by mthong** [codeforsanjose/economic-indicators-dashboard#57]

**Comment by LaurieSReynolds** [comment]
Would this be another column in the Unemployment data set?

**Comment by mthong** [comment]
Yes. One or two columns. I suppose the number of series (columns) and their labels could be specified in the chart config file, or potentially, for any line chart, the code would automatically draw as many lines as there are columns. We'd need a legend whenever there's more than one column -- or that can simply be specified in the config file.

**Comment by mthong** [comment]
Beautifully done!
