### ISSUE TITLE
Make green header and footer bars consistent

### ISSUE THREAD

**Issue by mthong** [codeforsanjose/economic-indicators-dashboard#71]
There are some inconsistencies in how the headers and footers appear. 

In my Chrome browser (Version 49.0.2623.112)

1. The dashboard header has rounded corners and there's a few pixels of white space on all three sides of the header that touch the browser window (left, top, right). 
2. The dashboard footer has sharp corners and there's a few pixels of white space on the left and right only, not on the bottom. 
3. The "About" page header and footer have NO white space on the three sides that touch the edge of the browser window (and I can't tell if the corners are rounded or not).

**Comment by golgistudio** [comment]
Item #3 has been addresded  - the about page was updated to match the index.html
