### ISSUE TITLE
Reduce width of left column on About page

### ISSUE THREAD

**Issue by mthong** [codeforsanjose/economic-indicators-dashboard#74]
The width of the left margin (span3 i think?) is a holdover from the about page we copied over as the basis for ours, which had a table of contents in the left column. I think it can be narrowed.

**Comment by golgistudio** [comment]
Eliminated the extra side spacing, so now it is the same when the browser width is resized.

http://codeforsanjose.github.io/economic-indicators-dashboard/about.html#/

**Comment by golgistudio** [comment]
I think some spacing on either side would look better

**Comment by mthong** [comment]
Looks good.
