### ISSUE TITLE
Make date formatting consistent among charts/indicators

### ISSUE THREAD

**Issue by mthong** [codeforsanjose/economic-indicators-dashboard#83]
Some are formatted as month-year, others as mm/dd/yy.

Try to fix first in source files consistent. 

Also coordinate with @golgistudio to understand how date formatting works with charting library.

**Comment by LaurieSReynolds** [comment]
Dates are treated as strings and are displayed as is.

**Comment by mthong** [comment]
This problem is addressed on the data side, not in the code. It has mostly been addressed in the existing datasets.
