### ISSUE TITLE
Improved visuals/transitions for detailed dashboard info (show which is open, and only have one open at a time)

### ISSUE THREAD

**Issue by juliemeridian** [codeforsanjose/economic-indicators-dashboard#86]
Two parts to this:
1. Improved visuals: since the show more/less toggle is pretty subtle, use a stronger border (3px) and a  green highlight ( rgba(170,193,37,1) ) to indicate which one's currently open.
2. Only show one section at a time. When someone clicks on a different section, do two changes immediately (make that section selected, and hide the previous section's data) and then fade in the newly selected section's data (I suggest after a 0.15s pause to fade it in over 0.5s)

Here's a movie that shows how these look:
https://www.dropbox.com/s/9ca7h8lcusxj8ww/Dashboard_DetailedInfo_transition.m4v?dl=0

**Comment by golgistudio** [comment]
Implemented

**Comment by mthong** [comment]
Nice work, @novavex! 
Great suggestion, @juliemeridian.
