### ISSUE TITLE
Implement more regular intervals for chart x-axes tick marks

### ISSUE THREAD

**Issue by mthong** [codeforsanjose/economic-indicators-dashboard#88]
The time series charts have dates along the x-axes but the labeled intervals seem a bit random rather than regular (E.g. every other January).

**Comment by golgistudio** [comment]
Preliminary implementation - currently set to 10 - need to discuss desired behavior

**Comment by mthong** [comment]
Suggest setting interval to 12 so that the labels are all for the same month each year.

**Comment by LaurieSReynolds** [comment]
Adjusted - to be the number of points / 12

**Comment by mthong** [comment]
The current settings are not showing the desired behavior. For all the monthly time series charts, I'd like the axis ticks/labels to be at January 20XX. 

Dividing the number of points by 12 won't get us to that behavior because every quarter I'll be adding three more months to each data set.   

If possible, setting the interval to 12 should work because January is always at the start of the time series.

**Comment by golgistudio** [comment]
Better?

**Comment by mthong** [comment]
Ultimately, I think the tick interval needs to be added as a config option in charts_config.json, because different intervals will be needed for different datasets. For example, the apartment rent and vacancy charts are quarterly, so the interval of 12 doesn't work as well - an interval of 4 would probably be better for quarterly data. If it's easier for now we could just hardcode the quarterly rent data to use an interval of 4 instead?

**Comment by golgistudio** [comment]
I won't be able to work on it this weekend.

**Comment by mthong** [comment]
No problem!
