### ISSUE TITLE
Chart titles renders twice and overlaps when browser windows is rescaled

### ISSUE THREAD

**Issue by golgistudio** [codeforsanjose/economic-indicators-dashboard#89]
1) Navigate to the dashboard in a browser that is scaled fairly wide
2) Display a line chart (e.g.  Total jobs)
3) Resize the width of the browser to make it narrower.  You'll notice that the chart rescales and everything seems to look ok.
4) Dismiss the chart by click on the 'see less'
5) Display the same chart again and you'll see the overlapping

Work around - refresh the browser
<img width="786" alt="screen shot 2016-06-26 at 1 29 25 pm" src="https://cloud.githubusercontent.com/assets/5599690/16364695/80c01ea8-3ba2-11e6-9922-7664ae40a72b.png">

**Comment by mthong** [comment]
Thanks for fixing this, @chandnisoni! Great work.
