### ISSUE TITLE
Axis and tooltip labels for prices should show '$'

### ISSUE THREAD

**Issue by golgistudio** [codeforsanjose/economic-indicators-dashboard#90]
<img width="995" alt="screen shot 2016-06-26 at 1 31 08 pm" src="https://cloud.githubusercontent.com/assets/5599690/16364699/9e484bc6-3ba2-11e6-8147-5285fe5b1a9c.png">

The axis labels and tooltip labels are currently pulled from the data which have the '$' stripped.  Would like the '$' restored on the axis labels and tooltips.

**Comment by mthong** [comment]
$ are now added in but a side-effect seems to be that the commas not being added back in for formatting purposes - see issue #121.
